Palestra_ASP/Palestra_ASP/Models/Corso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Palestra_ASP.Models
{
    [Table("Corsi")]
    public class Corso
    {
        [Column("Id")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int Id { get; set; }



        [NotMapped]
        public string Cod_C { get; set; }
        public Corso()
        {
            Cod_C = Guid.NewGuid().ToString();
        }




        [Column("Titolo")]
        [Required]
        [StringLength(50)]
        public string Titolo { get; set; }



        [Column("Descrizione")]
        [Required]
        [StringLength(255)]
        public string Descrizione { get; set; }



        [Column("Codice")]
        [Required]
        public string Codice { get; set; }


        [Column("Data")]
        [Required]
        public DateTime Data { get; set; }




        
        public ICollection<Utente> Utenti { get; set; }
    }
}

Palestra_ASP/Palestra_ASP/Models/Iscrizione.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Palestra_ASP.Models
{
    [Table("Iscrizioni")]
    public class Iscrizione
    {
        
        //[Column("IdCorso")]
        
        [ForeignKey("IdCorso")]
        public Corso Corso { get; set; }




        [ForeignKey("IdUtente")]
        public Utente Utente { get; set; }

    }
}

Palestra_ASP/Palestra_ASP/Models/Utente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Palestra_ASP.Models
{
    [Table("Utenti")]
    public class Utente
    {
        [Column("Id")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }




        [NotMapped]
        public string Cod_U { get; set; }
        public Utente()
        {
            Cod_U = Guid.NewGuid().ToString();
        }




        [Column("Nome")]
        [Required(ErrorMessage = "Il campo Nome è obbligatorio")]
        [StringLength(50, ErrorMessage = "Il campo Nome è troppo lungo")]
        public string Nome { get; set; }


        [Column("Cognome")]
        [Required(ErrorMessage = "Il campo Nome è obbligatorio")]
        [StringLength(50, ErrorMessage = "Il campo Cognome è troppo lungo")]
        public string Cognome { get; set; }


        [Column("Indirizzo")]
        [Required(ErrorMessage = "Il campo Indirizzo è obbligatorio")]
        public string Indirizzo { get; set; }


        [Column("D_Nascita")]
        [Required(ErrorMessage = "Il campo 'Data di Nascita' è obbligatorio")]
        public string D_Nascita { get; set; }


        [Column("Username")]
        [Required(ErrorMessage = "Il campo Username è obbligatorio")]
        [MinLength(3, ErrorMessage = "Il campo Username è troppo corto")]
        [StringLength(50, ErrorMessage = "Il campo Username è troppo lungo")]
        public string Username { get; set; }


        [Column("Password")]
        [Required(ErrorMessage = "Il campo Password è obbligatorio")]
        [StringLength(50, ErrorMessage = "Il campo Password è troppo lungo")]
        public string Password { get; set; }


        [NotMapped]
        [Column("VerificaPwd")]
        [Required(ErrorMessage = "Il campo Verifica password è obbligatorio")]
        [StringLength(50, ErrorMessage = "Il campo Verifica password è troppo lungo")]
        public string VerificaPwd { get; set; }




        public ICollection<Corso> Corsi { get; set; }








    }
}

Palestra_ASP/Palestra_ASP/Controllers/CorsoController.cs
using Microsoft.AspNetCore.Mvc;
using Palestra_ASP.Data;
using Palestra_ASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Palestra_ASP.Controllers
{
    public class CorsoController : Controller
    {
        private readonly InterfaceRepo<Corso> _repositoryCor;
        



        public CorsoController(InterfaceRepo<Corso> repCor)
        {
            _repositoryCor = repCor;
        }






        //[HttpPost]
        public IActionResult ListaCorsi()
        {
            List<Corso> elenco = (List<Corso>)_repositoryCor.GetAll();

            ViewBag.Title = "Lista Corsi";

            return View(elenco);
        }












        [HttpPost]
        public IActionResult Inserisci(Corso objCor)
        {

            if (ModelState.IsValid)
            {
                _repositoryCor.Insert(objCor);
                return Redirect("/");
            }
            else
            {

                return View(objCor);
            }

        }








        public IActionResult Dettaglio(string varCod_C)
        {

            Corso temp = _repositoryCor.GetFromCodice(varCod_C);

            if (temp == null)
                return Redirect("Corso/Errore");

            return View(temp);
        }








        [HttpPost]
        public IActionResult Modifica(Corso objCor)
        {

            //TODO...
            return View();
        }







        [HttpDelete]
        public ActionResult Elimina(string varCod_C)
        {
            //TODO...
            return Ok(new { Status = "success" });
        }

    }
}

Palestra_ASP/Palestra_ASP/Controllers/UtenteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Palestra_ASP.Data;
using Palestra_ASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Palestra_ASP.Controllers
{
    public class UtenteController : Controller
    {

        private readonly InterfaceRepo<Utente> _repositoryUte;


        public UtenteController(InterfaceRepo<Utente> repUte)
        {
            _repositoryUte = repUte;
        }






        public IActionResult ListaUtenti()
        {
            List<Utente> elenco = (List<Utente>)_repositoryUte.GetAll();

            ViewBag.Title = "Lista Utenti";

            return View(elenco);
        }



        
        public IActionResult Login()
        {
            return View();

        }

        [HttpPost]
        private IActionResult Login(Utente objUte)
        {
                       

            return Ok(objUte);

        }





        [HttpPost]
        public IActionResult Iscrizione(Utente objUte)
        {
            if (ModelState.IsValid)
            {
                _repositoryUte.Insert(objUte);
                return Redirect("/");
            }
            else
            {

                return View(objUte);
            }

        }








        public IActionResult Dettaglio(string varCod_U)
        {
            Utente temp = _repositoryUte.GetFromCodice(varCod_U);

            if (temp == null)
                return Redirect("Utente/Errore");

            return View(temp);
        }





        [HttpPost]
        public IActionResult Modifica(Utente objUte)
        {

            //TODO...
            return View();
        }





        [HttpDelete]
        public ActionResult Elimina(string varCod_U)
        {
            //TODO...
            return Ok(new { Status = "success" });
        }







    }
}

Palestra_ASP/Palestra_ASP/Views/Corso/Dettaglio.cshtml
@model Palestra_ASP.Models.Corso
@{ Layout = "_Layout"; }

<div class="row">
    <div class="col">

        <form asp-controller="Corso" asp-action="Dettaglio" method="post">
            <div class="form-group">
                <label asp-for="Titolo">Titolo:</label>
                <input type="text" asp-for="Titolo" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Titolo"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descrizione">Descrizione:</label>
                <input type="text" asp-for="Descrizione" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Descrizione"></span>
            </div>

            <div class="form-group">
                <label asp-for="Codice">Codice:</label>
                <input type="text" asp-for="Codice" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Codice"></span>
            </div>

            <div class="form-group">
                <label asp-for="Data">Data:</label>
                <input type="text" asp-for="Data" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Data"></span>
            </div>

        </form>

    </div>
</div>

Palestra_ASP/Palestra_ASP/Views/Corso/ListaCorsi.cshtml
@model List<Palestra_ASP.Models.Corso>

@{ Layout = "_Layout"; }

<h1>Corsi Disponibili</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Titolo</th>
            <th>Descrizione</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Titolo</td>
                    <td>@item.Descrizione</td>

                    <td>
                        <a href="/Corso/Dettaglio/@item.Cod_C ">@item.Cod_C e</a>
                    </td>
                    <td>@item.Titolo</td>
                    <td>@item.Descrizione</td>
                    <td>@item.Codice</td>
                    <td>@item.Data</td>
                    <td>
                        <button type="button" class="btn btn-danger" onclick="eliminaCor('@item.Cod_C ')">Elim.</button>
                    </td>
                </tr>
            }

    </tbody>
</table>

Palestra_ASP/Palestra_ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
</head>
<body>



    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Palestra</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/Utente/Iscrizione">Iscriviti</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Utente/Login">Accedi</a>
                </li>
                
            </ul>
        </div>
    </nav>



    <div class="container">
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/script.js"></script>
</body>
</html>

Palestra_ASP/Palestra_ASP/Views/Utente/Iscrizione.cshtml
@model Palestra_ASP.Models.Utente
@{ Layout = "_Layout"; }

<div class="row">
    <div class="col">

        <form asp-controller="Utente" asp-action="Iscrizione" method="post">

            <div class="form-group">
                <label asp-for="Nome">Nome:</label>
                <input type="text" asp-for="Nome" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Nome"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cognome">Cognome:</label>
                <input type="text" asp-for="Cognome" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Cognome"></span>
            </div>

            <div class="form-group">
                <label asp-for="Indirizzo">Indirizzo:</label>
                <input type="text" asp-for="Indirizzo" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Indirizzo"></span>
            </div>

            <div class="form-group">
                <label asp-for="D_Nascita">Data di Nascita:</label>
                <input type="text" asp-for="D_Nascita" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="D_Nascita"></span>
            </div>


            <div class="form-group">
                <label asp-for="Username">Username:</label>
                <input type="text" asp-for="Username" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Username"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password">Password:</label>
                <input type="text" asp-for="Password" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Password"></span>
            </div>

            <div class="form-group">
                <label asp-for="VerificaPwd">Verifica Password:</label>
                <input type="text" asp-for="VerificaPwd" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="VerificaPwd"></span>
            </div>


            <button type="submit">Iscriviti</button>
        </form>

    </div>
</div>

Palestra_ASP/Palestra_ASP/Views/Utente/Login.cshtml
@model Palestra_ASP.Models.Utente
@{ Layout = "_Layout"; }

<div class="row">
    <div class="col">

        <form asp-controller="Utente" asp-action="Login" method="post">

            <div class="form-group">
                <label asp-for="Username">Username:</label>
                <input type="text" asp-for="Username" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Username"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password">Password:</label>
                <input type="text" asp-for="Password" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Password"></span>
            </div>

                        
            <button type="submit">Login</button>
        </form>

    </div>
</div>

Palestra_ASP/Palestra_ASP/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>